### ISSUE TITLE
can not launch the app already install

### ISSUE THREAD

**Issue by lixiangwei** [jasny/jquery.smartbanner#72]

**Comment by khennings** [comment]
I think @lixiangwei is saying, if the user already has the app downloaded, the banner's button should open that app, rather than still link to the store (for both iOS and Android).

**Comment by jasny** [comment]
This is not something that JavaScript can do directly.

You can do this using [intent filters](https://developer.android.com/training/app-indexing/deep-linking.html) in your app. Set the url of the app banner to your deep link. From that link redirect that user to the store in the browser. The link will be opened in the app (if installed) instead of the browser, thus giving the wanted behaviour.
